### PR TITLE
Add station_information sensor

### LINKED ISSUE #75: Add latitude/longitude sensor
Maybe a "location" sensor?

Do you accept PRs?

### PR DESCRIPTION
**Pull request by jcgoette**
Closes #75.

Obviously, I am open to any suggestions/edits/etc.

### CODE REVIEW

**Comment by briis** [comment]
Thanks Justin. This is now merged, and will be part of the next release.
Just for my understanding, what will you be using this sensor for?

**Comment by jcgoette** [comment]
Automation to check that station being queried doesn't relocate unexpectedly.

**Comment by briis** [comment]
> doesn't relocate unexpectedly

Excuse my ignorance, but how can that happen?

**Comment by jcgoette** [comment]
Not at all. Very well could be my ignorance...

If owner of station is renter, if they sell their current home, etc.

**Comment by briis** [comment]
Got it.

**Pull request merged**
